# Generated by Django 5.2.3 on 2025-06-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='task_label', to='labels.label', verbose_name='Метки'),
        ),
    ]
