name: my check

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0 
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
        # make depends on uv
      - name: Install dependencies
        run: |
          pip install uv
          uv venv
          source .venv/bin/activate
          uv pip install -r requirements.txt
  
      - name: Make migrations
        run: make migrate

      - name: Run linter and pytest
        env:
            DATABASE_URL: "sqlite:///db.sqlite3"
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          uv run coverage run --source='task_manager' manage.py test --keepdb
          uv run coverage lcov -o coverage.lcov

      - name: QLTY_COV  
        uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{secrets.QLTY_COVERAGE_TOKEN}}
          files: coverage.lcov
