name: my check

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0 
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
        # make depends on uv
      - name: Install dependencies
        run: |
          pip install uv
          uv venv
          source .venv/bin/activate
          uv pip install -r requirements.txt
  
      - name: Make migrations
        run: make migrate

      - name: Run linter and pytest
        env:
            DATABASE_URL: "sqlite:///db.sqlite3"
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          uv run coverage run --source='task_manager' manage.py test
          uv run coverage xml -o coverage.xml

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          scanner: "external"
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.scanner.force-external=true