name: my check

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
        # make depends on uv
      - name: Install dependencies
        run: |
          pip install uv
          make install
          pip install pytest pytest-cov

      - name: Make migrations
        run: make migrate

      - name: Run tests with coverage
        env:
          DATABASE_URL: "sqlite:///db.sqlite3"
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          pytest --cov=./ --cov-report=xml:coverage.xml

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=.
            -Dsonar.exclusions=**/migrations/**,**/tests/**
      - name: Make migrations
        run: make migrate

      - name: Run linter and pytest
        env:
            DATABASE_URL: "sqlite:///db.sqlite3"
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          make check